//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samico.ServiceSAC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicio.DA.org/", ConfigurationName="ServiceSAC.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _clave del espacio de nombres http://Servicio.DA.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio.DA.org/CambiarClaveTelefono", ReplyAction="*")]
        Samico.ServiceSAC.CambiarClaveTelefonoResponse CambiarClaveTelefono(Samico.ServiceSAC.CambiarClaveTelefonoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio.DA.org/CambiarClaveTelefono", ReplyAction="*")]
        System.Threading.Tasks.Task<Samico.ServiceSAC.CambiarClaveTelefonoResponse> CambiarClaveTelefonoAsync(Samico.ServiceSAC.CambiarClaveTelefonoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _user del espacio de nombres http://Servicio.DA.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio.DA.org/Login", ReplyAction="*")]
        Samico.ServiceSAC.LoginResponse Login(Samico.ServiceSAC.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio.DA.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<Samico.ServiceSAC.LoginResponse> LoginAsync(Samico.ServiceSAC.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CambiarClaveTelefonoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CambiarClaveTelefono", Namespace="http://Servicio.DA.org/", Order=0)]
        public Samico.ServiceSAC.CambiarClaveTelefonoRequestBody Body;
        
        public CambiarClaveTelefonoRequest() {
        }
        
        public CambiarClaveTelefonoRequest(Samico.ServiceSAC.CambiarClaveTelefonoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Servicio.DA.org/")]
    public partial class CambiarClaveTelefonoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _clave;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _opcion;
        
        public CambiarClaveTelefonoRequestBody() {
        }
        
        public CambiarClaveTelefonoRequestBody(string _clave, string _opcion) {
            this._clave = _clave;
            this._opcion = _opcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CambiarClaveTelefonoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CambiarClaveTelefonoResponse", Namespace="http://Servicio.DA.org/", Order=0)]
        public Samico.ServiceSAC.CambiarClaveTelefonoResponseBody Body;
        
        public CambiarClaveTelefonoResponse() {
        }
        
        public CambiarClaveTelefonoResponse(Samico.ServiceSAC.CambiarClaveTelefonoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Servicio.DA.org/")]
    public partial class CambiarClaveTelefonoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CambiarClaveTelefonoResult;
        
        public CambiarClaveTelefonoResponseBody() {
        }
        
        public CambiarClaveTelefonoResponseBody(string CambiarClaveTelefonoResult) {
            this.CambiarClaveTelefonoResult = CambiarClaveTelefonoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://Servicio.DA.org/", Order=0)]
        public Samico.ServiceSAC.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Samico.ServiceSAC.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Servicio.DA.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _pass;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string _user, string _pass) {
            this._user = _user;
            this._pass = _pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://Servicio.DA.org/", Order=0)]
        public Samico.ServiceSAC.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Samico.ServiceSAC.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Servicio.DA.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Samico.ServiceSAC.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Samico.ServiceSAC.Service1Soap>, Samico.ServiceSAC.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Samico.ServiceSAC.CambiarClaveTelefonoResponse Samico.ServiceSAC.Service1Soap.CambiarClaveTelefono(Samico.ServiceSAC.CambiarClaveTelefonoRequest request) {
            return base.Channel.CambiarClaveTelefono(request);
        }
        
        public string CambiarClaveTelefono(string _clave, string _opcion) {
            Samico.ServiceSAC.CambiarClaveTelefonoRequest inValue = new Samico.ServiceSAC.CambiarClaveTelefonoRequest();
            inValue.Body = new Samico.ServiceSAC.CambiarClaveTelefonoRequestBody();
            inValue.Body._clave = _clave;
            inValue.Body._opcion = _opcion;
            Samico.ServiceSAC.CambiarClaveTelefonoResponse retVal = ((Samico.ServiceSAC.Service1Soap)(this)).CambiarClaveTelefono(inValue);
            return retVal.Body.CambiarClaveTelefonoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Samico.ServiceSAC.CambiarClaveTelefonoResponse> Samico.ServiceSAC.Service1Soap.CambiarClaveTelefonoAsync(Samico.ServiceSAC.CambiarClaveTelefonoRequest request) {
            return base.Channel.CambiarClaveTelefonoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Samico.ServiceSAC.CambiarClaveTelefonoResponse> CambiarClaveTelefonoAsync(string _clave, string _opcion) {
            Samico.ServiceSAC.CambiarClaveTelefonoRequest inValue = new Samico.ServiceSAC.CambiarClaveTelefonoRequest();
            inValue.Body = new Samico.ServiceSAC.CambiarClaveTelefonoRequestBody();
            inValue.Body._clave = _clave;
            inValue.Body._opcion = _opcion;
            return ((Samico.ServiceSAC.Service1Soap)(this)).CambiarClaveTelefonoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Samico.ServiceSAC.LoginResponse Samico.ServiceSAC.Service1Soap.Login(Samico.ServiceSAC.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string _user, string _pass) {
            Samico.ServiceSAC.LoginRequest inValue = new Samico.ServiceSAC.LoginRequest();
            inValue.Body = new Samico.ServiceSAC.LoginRequestBody();
            inValue.Body._user = _user;
            inValue.Body._pass = _pass;
            Samico.ServiceSAC.LoginResponse retVal = ((Samico.ServiceSAC.Service1Soap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Samico.ServiceSAC.LoginResponse> Samico.ServiceSAC.Service1Soap.LoginAsync(Samico.ServiceSAC.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Samico.ServiceSAC.LoginResponse> LoginAsync(string _user, string _pass) {
            Samico.ServiceSAC.LoginRequest inValue = new Samico.ServiceSAC.LoginRequest();
            inValue.Body = new Samico.ServiceSAC.LoginRequestBody();
            inValue.Body._user = _user;
            inValue.Body._pass = _pass;
            return ((Samico.ServiceSAC.Service1Soap)(this)).LoginAsync(inValue);
        }
    }
}
