//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samico.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class AgentRequestNotification
    {
        public int RequestId { get; set; }
        public string ConnectionId { get; set; }
        public string RequesterName { get; set; }
        public string RequesterGroup { get; set; }
        public string AgentName { get; set; }
        public Nullable<bool> AttendedByAgent { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<System.DateTime> AttendedByAgentDate { get; set; }

        [JsonIgnore]
        [IgnoreDataMember]
        public virtual Compania Compania { get; set; }
    }
}
