//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int IdChat { get; set; }
        public int IdSesion { get; set; }
        public Nullable<bool> Pregunta { get; set; }
        public string Texto { get; set; }
        public Nullable<bool> MsgBot { get; set; }
        public Nullable<decimal> Score { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual HistoricoSesion HistoricoSesion { get; set; }
    }
}
