//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatReportSami
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public Nullable<int> IdSesion { get; set; }
        public string Pregunta { get; set; }
        public string Respuesta { get; set; }
        public Nullable<bool> Resuelto { get; set; }
        public Nullable<bool> Satisfecho { get; set; }
        public string Formato_Luis { get; set; }
        public string S_O { get; set; }
        public string Intencion { get; set; }
        public string Entidad { get; set; }
        public string No_Caso { get; set; }
        public string Estado_Caso { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public string IdUsuario { get; set; }
        public string Puntaje_LUIS { get; set; }
        public string Puntaje_QnA { get; set; }
        public string Plataforma { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
