//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConexionAgente
    {
        public int id { get; set; }
        public string IdUser { get; set; }
        public Nullable<System.DateTime> FechaConexion { get; set; }
        public Nullable<System.DateTime> FechaDesconexion { get; set; }
    }
}
