//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contexto
    {
        public int Id { get; set; }
        public string IdUser { get; set; }
        public string ticketId { get; set; }
        public string result { get; set; }
    
        public virtual Contexto Contextos1 { get; set; }
        public virtual Contexto Contexto1 { get; set; }
    }
}
