//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntrenamientoQnA
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int Company { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Count { get; set; }
        public string Observaciones { get; set; }
    }
}
