//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samico.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SamiEntities : DbContext
    {
        public SamiEntities()
            : base("name=SamiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgentRequestNotification> AgentRequestNotifications { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CasosGenerado> CasosGenerados { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<ChatReportSami> ChatReportSamis { get; set; }
        public virtual DbSet<Compania> Companias { get; set; }
        public virtual DbSet<ConexionAgente> ConexionAgentes { get; set; }
        public virtual DbSet<ConexionCA> ConexionCAs { get; set; }
        public virtual DbSet<Contexto> Contextos { get; set; }
        public virtual DbSet<HistoricoSesion> HistoricoSesions { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<EntrenamientoQnA> EntrenamientoQnAs { get; set; }
        public virtual DbSet<ControlArchivo> ControlArchivos { get; set; }
        public virtual DbSet<ChatReportAgent> ChatReportAgents { get; set; }
        public virtual DbSet<ApiConversacion> ApiConversacions { get; set; }
    }
}
